#!/usr/bin/env bash
# =============================================================================
# code-review.sh — Step 7: post an automated checklist review comment on the PR
# Usage: npm run apply-issue:review -- <issue-number>
# =============================================================================
set -euo pipefail
STEPS_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
source "$STEPS_DIR/_lib.sh"

validate_issue_number "${1:-}" "apply-issue:review"
ISSUE_NUMBER="$1"
resolve_context

log_step "[7/7] Code review for issue #$ISSUE_NUMBER  →  $BRANCH"

PR_NUMBER="$(gh pr list --head "$BRANCH" --state open --json number -q '.[0].number' 2>/dev/null || echo '')"

if [[ -z "$PR_NUMBER" ]]; then
  log_warn "No open PR found for branch '$BRANCH'. Run apply-issue:pr first."
  exit 1
fi

DIFF_FILE="/tmp/pr_diff_${ISSUE_NUMBER}.txt"
gh pr diff "$PR_NUMBER" > "$DIFF_FILE" 2>/dev/null || true

if [[ ! -s "$DIFF_FILE" ]]; then
  log_warn "PR diff is empty — skipping review."
  exit 0
fi

log_info "PR #$PR_NUMBER diff captured ($(wc -l < "$DIFF_FILE") lines). Posting review..."

REVIEW_BODY="## 🤖 Automated Code Review — Issue #${ISSUE_NUMBER}

> Generated by \`apply-issue.sh\` after push to \`${BRANCH}\`

### Checklist
- [ ] All acceptance criteria from issue #${ISSUE_NUMBER} appear to be addressed
- [ ] No leftover TODO / FIXME comments
- [ ] No \`console.log\` debug statements committed
- [ ] Test file(s) included and covering the new logic
- [ ] Types are explicit — no unintentional \`any\`
- [ ] Styled Components use theme/CSS variables, not hardcoded values
- [ ] No unused imports

### Diff stats
\`\`\`
$(cd "$REPO_ROOT" && git diff origin/main..."$BRANCH" --stat 2>/dev/null || head -20 "$DIFF_FILE")
\`\`\`

> If any items above are unchecked, please address them before merging."

gh pr review "$PR_NUMBER" \
  --comment \
  --body "$REVIEW_BODY" 2>/dev/null \
  && log_success "Code review comment posted to PR #$PR_NUMBER" \
  || { log_warn "Could not post review. Check gh auth scopes (needs pull_requests: write)."; exit 1; }
